"""Regression cases for advisory rm wrapper parsing; commands are never executed."""

from __future__ import annotations

from collections.abc import Sequence

import pytest

from terminal_tools.common.destructive_warning import get_warning

# Expected results are pinned to the reviewed behavior, not calculated by the
# candidate. Includes original PR cases, option arity, quote/argv boundaries,
# and preservation of the non-rm catalog. See the review receipt for scope.
CASES: list[tuple[str | list[str], str | None]] = [
    ("sudo rm -rf /", "may recursively force-remove files"),
    ("doas rm -rf /", "may recursively force-remove files"),
    ("sudo -E rm -rf /home", "may recursively force-remove files"),
    ("sudo -u root rm -rf /srv", "may recursively force-remove files"),
    ("nohup rm -rf /data", "may recursively force-remove files"),
    ("time rm -rf /data", "may recursively force-remove files"),
    ("env rm -rf /data", "may recursively force-remove files"),
    ("FOO=1 rm -rf /", "may recursively force-remove files"),
    ("FOO=1 BAR=2 rm -rf /data", "may recursively force-remove files"),
    ("find . -name '*.pyc' | xargs rm -rf", "may recursively force-remove files"),
    ("make clean && sudo rm -rf build", "may recursively force-remove files"),
    ("sudo rm -r /var/log", "may recursively remove files"),
    ("sudo rm -f /var/log/x", "may force-remove files"),
    ("sudo rm -rf -- /", "may recursively force-remove files"),
    ("echo sudo rm -rf /", None),
    ("echo \"sudo rm -rf /\"", None),
    ("sudo apt update", None),
    ("sudo systemctl restart nginx", None),
    ("sudo docker ps", None),
    ("grep -r rm .", None),
    ("cat sudo_rm_notes.txt", None),
    ("sudo -n echo rm -rf /tmp/example", None),
    ("sudo -E echo rm -rf /tmp/example", None),
    ("sudo -H echo rm -rf /tmp/example", None),
    ("sudo -En echo rm -rf /tmp/example", None),
    ("sudo -S echo rm -rf /tmp/example", None),
    ("sudo -b echo rm -rf /tmp/example", None),
    ("doas -n echo rm -rf /tmp/example", None),
    ("env -i echo rm -rf /tmp/example", None),
    ("env -v echo rm -rf /tmp/example", None),
    ("env -iv echo rm -rf /tmp/example", None),
    ("command -p echo rm -rf /tmp/example", None),
    ("time -p echo rm -rf /tmp/example", None),
    ("xargs -0 echo rm -rf /tmp/example", None),
    ("xargs -r echo rm -rf /tmp/example", None),
    ("xargs -t echo rm -rf /tmp/example", None),
    ("xargs -0r echo rm -rf /tmp/example", None),
    ("sudo -n env -i echo rm -rf /tmp/example", None),
    ("sudo -u root env -i echo rm -rf /tmp/example", None),
    ("command -v rm -rf /tmp/example", None),
    ("command -V rm -rf /tmp/example", None),
    ("command -pv rm -rf /tmp/example", None),
    ("command -pV rm -rf /tmp/example", None),
    ("sudo -l rm -rf /tmp/example", None),
    ("sudo -v rm -rf /tmp/example", None),
    ("sudo -K rm -rf /tmp/example", None),
    ("doas -C /tmp/doas.conf rm -rf /tmp/example", None),
    ("nohup --help rm -rf /tmp/example", None),
    ("env --help rm -rf /tmp/example", None),
    ("xargs --help rm -rf /tmp/example", None),
    ("sudo -u rm echo -rf /tmp/example", None),
    ("sudo -u root echo rm -rf /tmp/example", None),
    ("sudo -nu root echo rm -rf /tmp/example", None),
    ("env -u rm echo -rf /tmp/example", None),
    ("env -u FOO echo rm -rf /tmp/example", None),
    ("env -uFOO echo rm -rf /tmp/example", None),
    ("env --unset=FOO echo rm -rf /tmp/example", None),
    ("xargs -E rm echo -rf /tmp/example", None),
    ("xargs -I '{}' echo rm -rf /tmp/example", None),
    ("xargs -n 2 echo rm -rf /tmp/example", None),
    ("time -o rm echo -rf /tmp/example", None),
    ("sudo -p 'prompt text' echo rm -rf /tmp/example", None),
    ("sudo -u rm -rf /tmp/example", None),
    ("sudo -n rm -rf /tmp/example", "may recursively force-remove files"),
    ("sudo -En rm -rf /tmp/example", "may recursively force-remove files"),
    ("sudo -nu root rm -rf /tmp/example", "may recursively force-remove files"),
    ("sudo -uroot rm -rf /tmp/example", "may recursively force-remove files"),
    ("sudo -p 'prompt text' rm -rf /tmp/example", "may recursively force-remove files"),
    ("sudo -- rm -rf /tmp/example", "may recursively force-remove files"),
    ("doas -nu root rm -rf /tmp/example", "may recursively force-remove files"),
    ("doas -u root rm -rf /tmp/example", "may recursively force-remove files"),
    ("nohup -- rm -rf /tmp/example", "may recursively force-remove files"),
    ("time -p rm -rf /tmp/example", "may recursively force-remove files"),
    ("\"time\" -o /tmp/time.out rm -rf /tmp/example", "may recursively force-remove files"),
    ("command -p rm -rf /tmp/example", "may recursively force-remove files"),
    ("command -- rm -rf /tmp/example", "may recursively force-remove files"),
    ("env -i rm -rf /tmp/example", "may recursively force-remove files"),
    ("env -u FOO rm -rf /tmp/example", "may recursively force-remove files"),
    ("env -uFOO rm -rf /tmp/example", "may recursively force-remove files"),
    ("env -C /tmp rm -rf /tmp/example", "may recursively force-remove files"),
    ("env --ignore-environment rm -rf /tmp/example", "may recursively force-remove files"),
    ("env --unset=FOO rm -rf /tmp/example", "may recursively force-remove files"),
    ("env --chdir /tmp rm -rf /tmp/example", "may recursively force-remove files"),
    ("env -- rm -rf /tmp/example", "may recursively force-remove files"),
    ("xargs -0 rm -rf /tmp/example", "may recursively force-remove files"),
    ("xargs -0n 2 rm -rf /tmp/example", "may recursively force-remove files"),
    ("xargs -n2 rm -rf /tmp/example", "may recursively force-remove files"),
    ("xargs -E STOP rm -rf /tmp/example", "may recursively force-remove files"),
    ("xargs -I '{}' rm -rf /tmp/example", "may recursively force-remove files"),
    ("sudo env FOO=1 rm -rf /tmp/example", "may recursively force-remove files"),
    ("FOO= rm -rf /tmp/example", "may recursively force-remove files"),
    ("FOO='two words' rm -rf /tmp/example", "may recursively force-remove files"),
    ("FOO=\"two words\" rm -rf /tmp/example", "may recursively force-remove files"),
    ("FOO=1 BAR=2 sudo -n env -i rm -rf /tmp/example", "may recursively force-remove files"),
    ("rm -rf /tmp/example", "may recursively force-remove files"),
    ("rm -fr /tmp/example", "may recursively force-remove files"),
    ("rm -r /tmp/example", "may recursively remove files"),
    ("rm -f /tmp/example", "may force-remove files"),
    ("rm /tmp/example", None),
    ("echo hello; rm -rf /tmp/example", "may recursively force-remove files"),
    ("git reset --hard", "may discard uncommitted changes"),
    ("git push --force", "may overwrite remote history"),
    ("git push --force-with-lease", "may overwrite remote history"),
    ("git push -f", "may overwrite remote history"),
    ("git clean -fd", "may permanently delete untracked files"),
    ("git clean -nfd", None),
    ("git clean --dry-run -fd", None),
    ("git checkout -- .", "may discard all working tree changes"),
    ("git checkout .", "may discard all working tree changes"),
    ("git restore .", "may discard all working tree changes"),
    ("git stash drop", "may permanently remove stashed changes"),
    ("git stash clear", "may permanently remove stashed changes"),
    ("git branch -D topic", "may force-delete a branch"),
    ("git commit --no-verify", "may skip safety hooks"),
    ("git merge --no-verify", "may skip safety hooks"),
    ("git commit --amend", "may rewrite the last commit"),
    ("DROP TABLE records", "may drop or truncate database objects"),
    ("TRUNCATE TABLE records", "may drop or truncate database objects"),
    ("DELETE FROM records;", "may delete rows from a database table"),
    ("kubectl delete pod test", "may delete Kubernetes resources"),
    ("terraform destroy", "may destroy Terraform infrastructure"),
    ("git status", None),
    ("git diff", None),
    ("git clean -n", None),
    ("git log", None),
    ("kubectl get pods", None),
    ("terraform plan", None),
    ("", None),
    (["sudo", "rm", "-rf", "/tmp/example"], "may recursively force-remove files"),
    (["sudo", "-n", "echo", "rm", "-rf", "/tmp/example"], None),
    (["env", "-i", "echo", "rm", "-rf", "/tmp/example"], None),
    (["command", "-v", "rm", "-rf", "/tmp/example"], None),
    (["sudo", "-u", "root", "rm", "-rf", "/tmp/example"], "may recursively force-remove files"),
    ("time -p FOO=1 rm -rf /tmp/example", "may recursively force-remove files"),
    ("time -- FOO=1 rm -rf /tmp/example", "may recursively force-remove files"),
    ("time -p -- FOO=1 rm -rf /tmp/example", "may recursively force-remove files"),
    ("time time FOO=1 rm -rf /tmp/example", "may recursively force-remove files"),
    ("time \"FOO=1\" rm -rf /tmp/example", None),
    ("\"time\" FOO=1 rm -rf /tmp/example", None),
    ("FOO=1 time BAR=2 rm -rf /tmp/example", None),
    ("sudo time FOO=1 rm -rf /tmp/example", None),
    (["time", "FOO=1", "rm", "-rf", "/tmp/example"], None),
    (["time", "-o", "/tmp/time.out", "rm", "-rf", "/tmp/example"], "may recursively force-remove files"),
    ("time -o /tmp/time.out rm -rf /tmp/example", None),
    ("time \"rm\" -rf /tmp/example", "may recursively force-remove files"),
    ("time FOO=1 sudo -n echo rm -rf /tmp/example", None),
    ("rm 'text; rm -rf /tmp/example'", None),
    (["rm", "plain", "; rm -rf /tmp/example"], None),
    ("sudo rm plain 'text; rm -rf /tmp/example'", None),
    ("rm -r 'text; rm -rf /tmp/example'", "may recursively remove files"),
    ("rm -f 'text; rm -rf /tmp/example'", "may force-remove files"),
    ("echo \"text; sudo rm -rf /tmp/example\"", None),
    ("echo \"text; rm -rf /tmp/example\"", None),
    (["echo", "text; sudo rm -rf /tmp/example"], None),
    ("nohup FOO=1 rm -rf /tmp/example", None),
    ("command FOO=1 rm -rf /tmp/example", None),
    ("time FOO=1 rm -rf /tmp/example", "may recursively force-remove files"),
    ("xargs FOO=1 rm -rf /tmp/example", None),
    ("'FOO=1' rm -rf /tmp/example", None),
    ("\"FOO=1\" rm -rf /tmp/example", None),
    ("'FOO'=1 rm -rf /tmp/example", None),
    ("FOO\\=1 rm -rf /tmp/example", None),
    (["FOO=1", "rm", "-rf", "/tmp/example"], None),
    (["env", "FOO=1", "rm", "-rf", "/tmp/example"], "may recursively force-remove files"),
    ("env \"FOO=1\" rm -rf /tmp/example", "may recursively force-remove files"),
    ("sudo \"FOO=1\" rm -rf /tmp/example", "may recursively force-remove files"),
    ("FOO=\"a; sudo rm -rf /tmp/example\" echo ok", None),
    ("env FOO=\"a; sudo rm -rf /tmp/example\" echo ok", None),
    ("sudo -p \"a; rm -rf /tmp/example\" echo ok", None),
    ("echo \";\" sudo rm -rf /tmp/example", None),
    ("echo \"&&\" sudo rm -rf /tmp/example", None),
    ("echo \"|\" sudo rm -rf /tmp/example", None),
    ("echo \"(sudo rm -rf /tmp/example)\"", None),
    ("echo \"x\nsudo rm -rf /tmp/example\"", None),
    ("echo x\\; sudo rm -rf /tmp/example", None),
    ("echo \"text; sudo rm -rf /tmp/example\"; rm -rf /tmp/actual", "may recursively force-remove files"),
    ("echo x && sudo rm -rf /tmp/example", "may recursively force-remove files"),
    ("echo x || sudo rm -rf /tmp/example", "may recursively force-remove files"),
    ("echo x; sudo rm -rf /tmp/example", "may recursively force-remove files"),
    ("printf x | xargs rm -rf /tmp/example", "may recursively force-remove files"),
    ("echo x\nsudo rm -rf /tmp/example", "may recursively force-remove files"),
    ("(sudo rm -rf /tmp/example)", "may recursively force-remove files"),
    ("  \t sudo rm -rf /tmp/example", "may recursively force-remove files"),
    ("# sudo rm -rf /tmp/example", None),
    ("echo x # sudo rm -rf /tmp/example", None),
    ("# comment\nsudo rm -rf /tmp/example", "may recursively force-remove files"),
    ("sudo rm -rf /tmp/example # comment", "may recursively force-remove files"),
    ("su\\\ndo rm -rf /tmp/example", "may recursively force-remove files"),
    ("sudo \\\nrm -rf /tmp/example", "may recursively force-remove files"),
    ("rm -rf /tmp/exam\\\nple", "may recursively force-remove files"),
    ("\"su\\\ndo\" rm -rf /tmp/example", "may recursively force-remove files"),
    ("'su\\\ndo' rm -rf /tmp/example", None),
    ("\\rm -rf /tmp/example", "may recursively force-remove files"),
    ("sudo 'rm' -rf /tmp/example", "may recursively force-remove files"),
    (["echo", ";", "sudo", "rm", "-rf", "/tmp/example"], None),
    (["echo", "x\nsudo rm -rf /tmp/example"], None),
    (["rm", "--", "-rf"], None),
    (["sudo", "--", "rm", "-rf", "/tmp/example"], "may recursively force-remove files"),
    (["sudo", "-u", "root", "echo", "rm", "-rf", "/tmp/example"], None),
    (["rm", "-rf", "/tmp/name; sudo rm -r other"], "may recursively force-remove files"),
    (["rm", "-rf /tmp/example"], None),
    ([], None),
    ([""], None),
    ("sudo -u", None),
    ("sudo --", None),
    ("env -u", None),
    ("sudo -u \"unterminated rm -rf /tmp/example", None),
]


@pytest.mark.parametrize(("command", "expected"), CASES)
def test_destructive_warning_prefix_boundaries(command: str | Sequence[str], expected: str | None) -> None:
    """An advisory must describe the executable, not words inside its arguments."""
    assert get_warning(command) == expected
